from swesmith.profiles import registry
from swesmith.harness.eval import run_evaluation
from swe_env.utils import parse_tool_call, execute_in_container, parse_complete_signal
from swe_env.constants import SYS_PROMPT, get_tool, get_user_prompt
from dataclasses import dataclass, field
from typing import Dict, Any, List, Tuple, Optional
import time
import re
import asyncio
import base64
import functools
import shlex

# def swap_context(summarize: dict, messages: list[dict], user_request: str) -> list[dict]:
#     assert messages[0]['role'] == "system", f"Message[0] role {messages[0]['role']} is incorrect, should be system"
#     system_prompt = messages[0]
#     next_session = summarize["next_session_context"]
#     think = summarize["think"]
#     summary_content = (
# f"""
# # User Request
# {user_request}

# <Important> You just called ClearContextTool, check the message from Previous Context </Important>
# # Previous Context
# {next_session}
# """
#     )
#     new_message = [
#         system_prompt,
#         {"role": "user", "content": f"You called ClearContextTool, the new context is\n{summary_content}"}
#     ]
    
#     return new_message

def detect_potential_cheating(command: str) -> Tuple[bool, Optional[str]]:
    """
    Analyzes a bash command to detect potential cheating behaviors in SWE tasks.
    
    Checks for:
    1. Accessing external repositories (GitHub/GitLab/Bitbucket).
    2. Attempting to access future commits or non-local history via git.
    3. Network calls that might fetch solutions.
    
    Args:
        command (str): The bash command generated by the model.
        
    Returns:
        Tuple[bool, str]: (is_cheating, reason). Returns (False, None) if safe.
    """
    
    # Normalize command for easier matching
    cmd_lower = command.lower().strip()
    
    # --- Pattern Definitions ---
    
    # 1. External Repository Access
    # Matches: git clone https://github.com/..., wget github.com/..., curl ...
    external_repo_pattern = r"(github\.com|gitlab\.com|bitbucket\.org)"
    
    # 2. Suspicious Git History Manipulation
    # We want to allow basic 'git status', 'git add', 'git commit', 'git diff' (local).
    # We want to flag 'git checkout <sha>', 'git log', 'git show' which might peek at the answer key.
    # Note: Adjust 'git checkout' strictness based on whether the agent needs to switch branches legitimately.
    suspicious_git_cmds = [
        r"git\s+clone",          # Cloning external repos
        r"git\s+fetch",          # Fetching upstream objects
        r"git\s+pull",           # Pulling upstream changes
        r"git\s+archive",        # Exporting code
        r"git\s+show",
        r"git\s+log",
        r"git\s+checkout\s+[0-9a-f]{7,40}", # Checking out specific commit hashes (potential future state)
    ]
    
    # 3. Network/Download Tools
    # Agents usually shouldn't need to download arbitrary files unless specified.
    network_tools = [
        r"\bwget\b",
        r"\bcurl\b",
        r"\bscp\b",
        r"\bssh\b",
        r"\bnc\b",    # netcat
    ]

    # --- Detection Logic ---

    # Check 1: Explicit External URLs
    if re.search(external_repo_pattern, cmd_lower):
        return True, "Detected attempt to access external repository (GitHub/GitLab)."

    # Check 2: Suspicious Git Commands
    for pattern in suspicious_git_cmds:
        if re.search(pattern, cmd_lower):
            return True, f"Detected suspicious git operation matching: {pattern}"

    # Check 3: Network Tools (Context Dependent)
    # If the pattern exists AND it targets an external URL (simplified heuristic)
    for tool in network_tools:
        if re.search(tool, cmd_lower):
            # Check if they are trying to hit an external site vs local
            if re.search(r"http[s]?://", cmd_lower):
                return True, f"Detected network tool '{tool.strip()}' accessing a URL."

    # Check 4: Looking for 'solution' or 'test_patch' files specifically
    # This is heuristic and depends on your repo structure.
    # sensitive_keywords = [r"solution", r"gold", r"answer"]
    # for kw in sensitive_keywords:
    #     # Matches 'cat solution.py', 'grep solution', etc.
    #     if re.search(rf"\b{kw}\b", cmd_lower):
    #          return True, f"Detected access to file with sensitive keyword: {kw}"

    return False, None

def swap_context(args, messages):
    assert messages[1]['role'] == 'user'
    assert messages[0]['role'] == 'system'
    
    mission_anchor = args.get("mission_anchor", "")
    acquired_knowledge = args.get("acquired_environmental_knowledge", "")
    pruned_paths = args.get("pruned_paths", "")
    immediate = args.get("immediate_next_step", "")
    others = args.get("others", "")
    
    form = (
f"""
Handoff Form From The Last Agent:

## Mission Anchor
{mission_anchor}

## Acquired Environmental Knowledge
{acquired_knowledge}

## Pruned Paths
{pruned_paths}

## Others
{others}

## Immediate Next Step
{immediate}
"""
    )
    
    new_ctx = (
        "You are going to continue the work from an Agent, the agent "
        "gave you the following handoff form:\n"
        f"{form}"
    )
    new_conversation = [
        messages[0].copy(),
        {"role": "user", "content": new_ctx}
    ]
    return new_conversation

def generate_patch(container):
    print("Generating patch...")
    cmd_list = [
        'cd /testbed',
        "git add -A",
        "git diff --cached > /testbed/model.patch",
        'cat /testbed/model.patch'
    ]
    for command in cmd_list:
        try:
            # Encode command to avoid shell escaping issues
            b64_cmd = base64.b64encode(command.encode('utf-8')).decode('utf-8')
            safe_cmd = f"bash -c 'timeout -k 5 40s bash -c \"echo {b64_cmd} | base64 -d | bash\"'"
            
            # Blocking call (no signal logic here)
            exit_code, output = container.exec_run(cmd=safe_cmd)
            
            # Decode output
            output_str = output.decode("utf-8", errors="replace")
            # print(f"\n[Tool Execution Completed] {command}")
            if exit_code != 0:
                print(f"Error generating patch: {output_str}")   
                break
                
            if command == cmd_list[-1]:
                # print(f"Patch:\n{output_str}")
                return output_str if output_str.strip() else None
            
        except Exception as e:
            print(f"Error executing command: {str(e)}")
            break
    return None

async def run_blocking(func, *args, **kwargs):
    """
    Helper to run blocking (synchronous) functions in a thread pool.
    """
    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(None, functools.partial(func, *args, **kwargs))

@dataclass
class StepResult:
    """Environment step execution result"""
    updated_message: list[dict]
    reward: float
    done: bool = field(default=False)
    success: bool = field(default=False)
    modified_context: bool = field(default=False)
    ################################
    # Add misbehave swap indicator #
    ################################
    misbehave_swap: bool = field(default=False)
    info: dict = field(default=None)

class SWEEnv:
    def __init__(self, task_instance: Dict, run_id: str):
        """
        Initialize the environment.
        :param task_instance: The specific task/issue to solve.
        :param registry: The registry object to fetch container providers (Dependency Injection).
        """
        self.task_instance = task_instance
        self.run_id = run_id
        self.rp = registry.get_from_inst(task_instance)
        print(f"Initializing container for task: {task_instance["instance_id"]}...")
        self.container = self.rp.get_container(task_instance, run_id)
        self.history: List[Dict[str, str]] = []
        
    def get_initial_prompt(self):
        tools = get_tool()
        user_prompt = get_user_prompt(".", self.task_instance["problem_statement"])
        self.user_prompt = user_prompt
        message = [
            {"role": "system", "content": SYS_PROMPT},
            {"role": "user", "content": user_prompt}
        ]
        
        return {"message": message, "tools": tools}

    def step(self, messages: List[Dict[str, str]], last_turn_budget: int) -> StepResult:
        """
        Executes a step in the environment based on the agent's message history.
        """
        # Ensure we are working with the latest state
        self.history = messages
        
        # 1. Validate Input
        if not messages or messages[-1]["role"] != "assistant":
            raise ValueError("The last message in the history must be from the assistant.")

        last_message = messages[-1]
        model_output = last_message.get("content", "")

        # 2. Check for Task Completion
        # if parse_complete_signal(model_output):
        #     # Important: first close the docker
        #     self.close()
        #     task_status = verify_task(model_output, self.task_instance, self.run_id)
        #     task_success = task_status["success"]
        #     return StepResult(
        #         updated_message=self.history,
        #         reward=1.0 if task_success else 0.0,
        #         done=True,
        #         success=task_success,
        #         info={"reason": "agent_submitted"}
        #     )

        # 3. Check for Tool Calls
        tool_call = parse_tool_call(model_output)
        
        if tool_call:
            return self._handle_tool_execution(tool_call, last_turn_budget)
        
        # 4. Fallback: No command found
        observation = "No valid command or completion signal detected. Please check your format."
        self._append_user_message(f"System Notification:\n{observation}")
        
        return StepResult(
            updated_message=self.history,
            reward=0.0,
            done=False,
            success=False,
            info={"reason": "no_command"}
        )

    def _handle_tool_execution(self, tool_call: Dict[str, Any], last_turn_budget: int) -> StepResult:
        """Internal helper to handle tool logic."""
        name = tool_call.get("name")
        args = tool_call.get("arguments", {})
        # print("*"*100)
        # print(name, args)
        # print("*"*100)
        try:
            if name == "HandoffTool":
                print(f"Detected Swap Tool!!!")
                # Assuming swap_context returns a NEW list of messages (compressed history)
                # We do not append an observation here, we replace the history.
                # new_history = swap_context(args, self.history, self.user_prompt)
                if int(last_turn_budget) > 3000:
                    # observation = f"Handoff with enough token budget ({last_turn_budget}) is rejected!"
                    # formatted_obs = f"Tool Execution Result:\n{observation}"
                    # print("Swap rejected!")
                    # Lynx: punish instead of reject
                    return StepResult(
                        updated_message=self.history,
                        reward=0,
                        done=False,
                        success=False,
                        modified_context=False,
                        misbehave_swap=True,
                        info={"reason": "Misbehaved swap"}
                    )
                    # self._append_user_message(formatted_obs)
                else:
                    new_history = swap_context(args, self.history)
                    return StepResult(
                        updated_message=new_history,
                        reward=0.0,
                        done=False,
                        success=False,
                        modified_context=True,
                        info={"reason": "memory_compressed"}
                    )

            elif name == "BashTool":
                command = args.get("command")
                cheating, reason = detect_potential_cheating(command)
                if cheating:
                    print(reason)
                    observation = "Error: Command blocked due to policy violation."
                else:
                    # print(f"{self.run_id} executing command {command}")
                    observation = asyncio.run(execute_in_container(self.container, command))
                formatted_obs = f"Tool Execution Result:\n{observation}"
                self._append_user_message(formatted_obs)
                
            elif name == "ReadFileTool":
                file_path = args.get("file_path")
                start_line = args.get("start_line")
                end_line = args.get("end_line")
                safe_path = shlex.quote(file_path)
                if start_line is not None or end_line is not None:
                    # Default start to 1 if only end is provided
                    s = start_line if start_line is not None else 1
                    
                    if end_line is not None:
                        # Read from s to e: sed -n '10,20p' file
                        command = f"sed -n '{s},{end_line}p' {safe_path}"
                    else:
                        # Read from s to the end: sed -n '10,$p' file
                        command = f"sed -n '{s},$p' {safe_path}"
                else:
                    # Standard full read
                    command = f"cat {safe_path}"

                observation = asyncio.run(execute_in_container(self.container, command))
                
                if "No such file or directory" in observation:
                    observation =  f"Error: The file '{file_path}' does not exist."
                    
                # Helpful metadata for the agent to know what they are looking at
                if start_line or end_line:
                    observation = f"--- Reading {file_path} (Lines {start_line if start_line else 1}-{end_line if end_line else 'EOF'}) ---\n{observation}"
                    
                formatted_obs = f"Tool Execution Result:\n{observation}"
                # print(formatted_obs)
                self._append_user_message(formatted_obs)
            
            elif name == "SubmitTool":
                task_status = asyncio.run(self._verify_task(self.task_instance, self.run_id))
                task_success = task_status["success"]
                return StepResult(
                    updated_message=self.history,
                    reward=1.0 if task_success else 0.0,
                    done=True,
                    success=task_success,
                    info={"reason": "agent_submitted"}
                )
            else:
                self._append_user_message(f"Error: Tool '{name}' is not supported.")

        except Exception as e:
            # Catch execution errors so the agent can try to recover
            error_msg = f"Runtime Error during tool execution: {str(e)}"
            self._append_user_message(error_msg)

        return StepResult(
            updated_message=self.history,
            reward=0.0,
            done=False,
            success=False,
            info={"reason": "tool_executed", "tool": name}
        )
        
    async def _verify_task(
        self,
        task_instance: dict, 
        run_id: str, 
        model_name: str = "Qwen3-Coder"
    ) -> dict:
        """
        Parses model output, extracts a patch, and runs evaluation.
        """
        print(f"Evaluating {run_id}")
        patch = generate_patch(self.container)
        if patch:
            # 3. Construct Payload
            prediction = {
                "instance_id": task_instance.get("instance_id"),
                "model_patch": patch,
                "model_name_or_path": model_name
            }

            payload = {
                "pred": prediction,
                "instance": task_instance,
                "run_id": run_id,
                "f2p_only": False,
                "is_gold": False
            }

            # 4. Execute Evaluation
            self.close()
            # Lynx: run_evaluation contains auto cleanup of the container
            # Lynx: Evaluation could also run infinitely, break long eval and set it unsolved.
            try:
                result = await asyncio.wait_for(
                    run_blocking(run_evaluation, **payload),
                    timeout=60.0
                )
            except Exception as e:
                print(f"Cannot evaluate due to {e}")
                result = dict(resolved=False)
            # result = run_evaluation(**payload)

            # 5. Determine Success
            # Success requires status to be completed AND resolved to be True
            is_success = result.get("resolved", False)
            # print("*"*100)
            # print(f"{patch}\nSuccess {is_success}")
            # print("*"*100)

            return {"success": is_success, "completed": True}
        
        return {"success": False, "completed": True}

    def _append_user_message(self, content: str):
        """Helper to append a message safely."""
        self.history.append({"role": "user", "content": content})

    # def close(self):
    #     """Clean up resources."""
    #     # Lynx: Should we use cleanup_container from swebench/harness/docker_utils.py?
    #     if self.container:
    #         try:
    #             self.container.stop()
    #             self.container.remove()
    #             print("Container stopped and removed.")
    #         except Exception as e:
    #             print(f"Error cleaning up container: {e}")
    #         finally:
    #             time.sleep(2) # Grace period

    #Kerwin: 修改 close 方法，防止重复调用
    def close(self):
        """Clean up resources."""
        if self.container is None:
            return  # 已清理，直接返回
        
        try:
            self.container.reload()  # 检查容器是否存在
            self.container.stop()
            self.container.remove()
            print("Container stopped and removed.")
        except Exception as e:
            # 容器可能已被 run_evaluation 清理
            print(f"Container cleanup: {e}")
        finally:
            self.container = None  # 标记已清理，防止重复调用
            time.sleep(2)
